import { useState } from 'react';
import { LockKeyhole } from 'lucide-react';
import { login, type AuthSession } from '@/lib/api';

export function AuthGate({ onAuthenticated }: { onAuthenticated: (session: AuthSession) => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [code, setCode] = useState(''); const [useRecoveryCode, setUseRecoveryCode] = useState(false); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  // The backend accepts either a 6-digit TOTP code or a recovery code in the
  // same field. Recovery codes are hexadecimal with a separating dash, so the
  // digits-only mask used for TOTP would make them impossible to type.
  function changeMode(recovery: boolean) { setUseRecoveryCode(recovery); setCode(''); setError(''); }
  function normalizeCode(value: string) { return useRecoveryCode ? value.toUpperCase().replace(/[^0-9A-F-]/g, '').slice(0, 11) : value.replace(/\D/g, ''); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { const session = await login({ email, password, totp_code: code || undefined }); localStorage.setItem('jury-auth-token', session.token); localStorage.setItem('jury-auth-user', JSON.stringify(session.user)); onAuthenticated(session); } catch { setError(useRecoveryCode ? 'Email, password, or recovery code is invalid.' : 'Email, password, or two-factor code is invalid.'); } finally { setLoading(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-muted/40 p-4"><form onSubmit={submit} className="w-full max-w-sm space-y-4 rounded-xl border bg-background p-6 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-lg bg-primary/10 p-2 text-primary"><LockKeyhole className="size-5" /></span><div><h1 className="font-semibold">Jury Assistant</h1><p className="text-sm text-muted-foreground">Secure sign in</p></div></div><label className="block text-sm">Email<input className="mt-1 h-10 w-full rounded-md border bg-background px-3" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label className="block text-sm">Password<input className="mt-1 h-10 w-full rounded-md border bg-background px-3" type="password" minLength={12} value={password} onChange={(e) => setPassword(e.target.value)} required /></label><label className="block text-sm">{useRecoveryCode ? 'Recovery code' : 'Two-factor code'} <span className="text-muted-foreground">(if enabled)</span><input className="mt-1 h-10 w-full rounded-md border bg-background px-3 font-mono" inputMode={useRecoveryCode ? 'text' : 'numeric'} autoComplete="one-time-code" placeholder={useRecoveryCode ? 'A1B2C-D3E4F' : '123456'} maxLength={useRecoveryCode ? 11 : 6} value={code} onChange={(e) => setCode(normalizeCode(e.target.value))} /></label><button type="button" className="text-xs text-muted-foreground underline underline-offset-2 hover:text-foreground" onClick={() => changeMode(!useRecoveryCode)}>{useRecoveryCode ? 'Use an authenticator code instead' : 'Lost your authenticator? Use a recovery code'}</button>{error && <p className="text-sm text-destructive">{error}</p>}<button className="h-10 w-full rounded-md bg-primary text-sm font-medium text-primary-foreground disabled:opacity-50" disabled={loading}>{loading ? 'Signing in…' : 'Sign in'}</button></form></main>;
}
