import { useState } from 'react';
import { LockKeyhole } from 'lucide-react';
import { login, type AuthSession } from '@/lib/api';

export function AuthGate({ onAuthenticated }: { onAuthenticated: (session: AuthSession) => void }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [code, setCode] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(''); try { const session = await login({ email, password, totp_code: code || undefined }); localStorage.setItem('jury-auth-token', session.token); localStorage.setItem('jury-auth-user', JSON.stringify(session.user)); onAuthenticated(session); } catch { setError('Email, password, or two-factor code is invalid.'); } finally { setLoading(false); } }
  return <main className="flex min-h-screen items-center justify-center bg-muted/40 p-4"><form onSubmit={submit} className="w-full max-w-sm space-y-4 rounded-xl border bg-background p-6 shadow-sm"><div className="flex items-center gap-3"><span className="rounded-lg bg-primary/10 p-2 text-primary"><LockKeyhole className="size-5" /></span><div><h1 className="font-semibold">Jury Assistant</h1><p className="text-sm text-muted-foreground">Secure sign in</p></div></div><label className="block text-sm">Email<input className="mt-1 h-10 w-full rounded-md border bg-background px-3" type="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label className="block text-sm">Password<input className="mt-1 h-10 w-full rounded-md border bg-background px-3" type="password" minLength={12} value={password} onChange={(e) => setPassword(e.target.value)} required /></label><label className="block text-sm">Two-factor code <span className="text-muted-foreground">(if enabled)</span><input className="mt-1 h-10 w-full rounded-md border bg-background px-3" inputMode="numeric" maxLength={6} value={code} onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))} /></label>{error && <p className="text-sm text-destructive">{error}</p>}<button className="h-10 w-full rounded-md bg-primary text-sm font-medium text-primary-foreground disabled:opacity-50" disabled={loading}>{loading ? 'Signing in…' : 'Sign in'}</button></form></main>;
}
