import { useEffect, useState } from 'react';
import { BellRing, Plus } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { createNotification, getNotifications, type Notification, type NotificationKind } from '@/lib/api';
import { useLocale } from '@/lib/locale-context';
import { useToast } from '@/lib/toast-context';

const kinds: NotificationKind[] = ['announcement', 'missing_document', 'deadline', 'review_task', 'result', 'question', 'faq'];
export function NotificationCenter() {
  const { t } = useLocale(); const { showToast } = useToast(); const [items, setItems] = useState<Notification[]>([]); const [title, setTitle] = useState(''); const [body, setBody] = useState(''); const [kind, setKind] = useState<NotificationKind>('announcement'); const [audience, setAudience] = useState('all'); const [category, setCategory] = useState(''); const [error, setError] = useState('');
  useEffect(() => { getNotifications().then(setItems).catch((e) => setError(e.message)); }, []);
  async function add() { if (!title.trim() || !body.trim()) return; try { const item = await createNotification({ title: title.trim(), body: body.trim(), kind, audience, category: category.trim() || null }); setItems((prev) => [item, ...prev]); setTitle(''); setBody(''); showToast(t('notificationCreated'), 'success'); } catch (e) { setError((e as Error).message); } }
  return <div className="space-y-6"><div><h1 className="text-xl font-semibold">{t('notificationCenterTitle')}</h1><p className="text-muted-foreground mt-1 text-sm">{t('notificationCenterDescription')}</p></div><Card><CardHeader><CardTitle className="flex items-center gap-2"><Plus className="size-4" />{t('createNotification')}</CardTitle></CardHeader><CardContent className="space-y-3"><div className="grid gap-3 md:grid-cols-[1fr_180px_180px_1fr]"><Input value={title} onChange={(e) => setTitle(e.target.value)} placeholder={t('notificationTitle')} /><select value={kind} onChange={(e) => setKind(e.target.value as NotificationKind)} className="h-9 rounded-md border bg-background px-3 text-sm">{kinds.map((item) => <option key={item} value={item}>{t(`notification_${item}`)}</option>)}</select><select value={audience} onChange={(e) => setAudience(e.target.value)} className="h-9 rounded-md border bg-background px-3 text-sm"><option value="all">{t('audienceAll')}</option><option value="jury_member">{t('role_jury_member')}</option><option value="chief_judge">{t('role_chief_judge')}</option><option value="competition_manager">{t('role_competition_manager')}</option></select><Input value={category} onChange={(e) => setCategory(e.target.value)} placeholder={t('notificationCategory')} /></div><Textarea value={body} onChange={(e) => setBody(e.target.value)} placeholder={t('notificationBody')} /><div className="flex justify-end"><button type="button" onClick={add} className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground">{t('publishNotification')}</button></div>{error && <p className="text-destructive text-sm">{error}</p>}</CardContent></Card><Card><CardHeader><CardTitle>{t('notificationHistory')}</CardTitle></CardHeader><CardContent className="space-y-2">{items.map((item) => <div key={item.id} className="rounded-md border p-3"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-medium">{item.title}</p><p className="text-muted-foreground mt-1 text-xs">{item.body}</p></div><span className="rounded-full bg-secondary px-2 py-1 text-[10px]">{t(`notification_${item.kind}`)}</span></div><p className="text-muted-foreground mt-2 text-[11px]">{item.audience}{item.category ? ` · ${item.category}` : ''} · {new Date(item.created_at).toLocaleString()}</p></div>)}{items.length === 0 && <p className="text-muted-foreground text-sm">{t('noNotifications')}</p>}</CardContent></Card></div>;
}
